### ISSUE TITLE
1.8 jest bezuzyteczny

### ISSUE THREAD

**Issue by asiekierka** [nabijaczleweli/ASMifier#1]
Taki protip od bardziej doswiadczonego. Rob pod 1.7.10, bo duzym modom sie nie chce przechodzic.

BTW - robilem cos zblizonego dawno temu na 1.5.2/1.6.2 -> https://github.com/asiekierka/moducomp

**Comment by nabijaczleweli** [comment]
Dzięki za protipa.
Trochę wpadłem na to, że 1.8 jeszcze (ogólnie) nie jest np. patrząc na `VillageRegistry` itp. klasy, ale porta zawsze dobrze mieć (nawet jeśli nowe `IModel`e i `ICustomModelLoader`y prawdopodobnie zniwelują potrzebę połowy tegoż) i jest to dobry pretekst do wybuchnięcia kawałka codebase'a.
Niebyt 1.8 spowodował również brak zmian tego "projektu" od 10.1.15.

BTW - imponujący ten moducomp.
<sub><i>W życiu bym nie wpadł na to, że ktoś tu zajrzy...</i></sub>

**Comment by asiekierka** [comment]
Następnym razem mnie nie followuj, jak nie chcesz niespodziewanych gosci.

**Comment by nabijaczleweli** [comment]
&#42;spamuje guzik do followania&#42;
Niespodziewany nie znaczy niechciany...

**Comment by nabijaczleweli** [comment]
&#42;

**Comment by nabijaczleweli** [comment]
Not anymore it ain't!
